version: '3'
# docker run -p 1234:3000 --name ui -e "NODE_ENV=production" --init -m "300M" --memory-swap "1G" -d ui
services:
  ui:
    build:
      context: .
    image: w3b3/web-app-001:latest
    container_name: ui
    hostname: ui
    labels:
      - "ca.codein=Web interface"
    volumes:
      - type: bind
        source: .
        target: /app
    networks:
      - youtube_api
#    init: true
#    restart: "on-failure:3"
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Etc/UTC
#      - NODE_ENV=development
        #    volumes:
        #      - /home/ds/containers/docker-volumes:/config
    env_file:
      - ./.env
    environment:
      - FOO=BUZZ
    expose:
      - 1234
    ports:
      - "1234:1234"
networks:
  youtube_api:
